controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

assistant_ask:
    path: /assistant/ask
    controller: App\Controller\AssistantController::askAssistant
