parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    materiel_image_directory: '%kernel.project_dir%/public/materielimage'

services:
    # Configuration par défaut pour l'autowiring
    _defaults:
        autowire: true
        autoconfigure: true

    # Injection automatique des services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Injection explicite des paramètres pour les contrôleurs
    App\Controller\UserController:
        arguments:
            $uploadsDirectory: '%uploads_directory%'

    App\Controller\MaterielRecyclableController:
        arguments:
             $projectDir: '%materiel_image_directory%'
